# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CicadaLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CicadaLive

pod 'Alamofire'
pod 'Kingfisher', '~> 7.0'

  target 'CicadaLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CicadaLiveUITests' do
    # Pods for testing
  end

end
